package com.dev.lakik.landlordmg.Common

/**
 * Created by ppash on 1/26/2018.
 */

enum class EnumFragments {
    LOGIN_FRAGMENT,
    REGISTRATION_FRAGMENT,
    FORGOT_PASS_FRAGMENT,
    PROPERTIES_FRAGMENT,
    CREATE_OR_EDIT_PROPERTY_FRAGMENT,
    PROPERTY_PRAGMENT,
    UNIT_FRAGMENT,
    CREATE_OR_EDIT_LEASE_FRAGMENT,
    CREATE_OR_EDIT_TENANT_FRAGMENT,
    VIEW_TENANT_FRAGMENT,
    LEASES_FRAGMENT,
    VIEW_CLOSED_LEASE_FRAGMENT,
    VIEW_ALL_TENANTS_FRAGMENT,
    LICENSE_FRAGMENT
}
enum class Action {
    CREATE, EDIT
}
